possible fix for "TypeError"
Possible fix for "TypeError: get_favorites() got an unexpected keyword argument 'retry'". I don't know if it breaks something important.